version: "3.8"
services:
    jenkins_docker: 
        image: docker:dind
        container_name: jenkins-docker
        privileged: true
        environment:
            DOCKER_TLS_CERTDIR: /certs 
        ports:
            - "2376:2376"
        volumes: 
            - ./jenkins-docker-certs:/certs/client
            - ./jenkins-data:/var/jenkins_home
        networks:
            - jenkins
        command: --storage-driver=overlay2


    jenkins:
        build: .
        container_name: jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        environment:
            DOCKER_HOST: tcp://docker:2376
            DOCKER_CERT_PATH: /certs/client
            DOCKER_TLS_VERIFY: 1 
        volumes:
            - ./jenkins-docker-certs:/certs/client:ro
            - ./jenkins-data:/var/jenkins_home
        networks:
            - jenkins


networks:
    jenkins: 
        driver: bridge